### ISSUE TITLE
We need a logo

### ISSUE THREAD

**Issue by idealhack** [magunetto/moviemagnetbot#4]
**Is your feature request related to a problem? Please describe.**
Currently, we don't have a logo.

**Describe the solution you'd like**
Hope someone could design one for this project, so we can use it for:

- organization avatar
- telegram avatar for bot, channel, group
- other cases

Each of these above could be not exactly same.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ggcarlosr** [comment]
Hi I have seen that they have opened this problem, I am a graphic designer and I would like to collaborate with a striking logo for you, let me know your concerns.

**Comment by zuuritaly** [comment]
Hello @idealhack  ,
I'm a graphic designer and I design logos for open source projects.

Usually I ask the following questions to assist me in the creative process:

Do you have something in your mind for the logo?
Do you want something specific for the logo?
What colors do you want in the logo?

With your answers I will design a logo for your project and if you like it you can keep it and used.

Best Regards

Zuur

**Comment by zuurritaly** [comment]
Hello @idealhack, how are you?
Im a graaphic designer and I would like to help with the design of the logo for this project if you want, I 

Cheers
Zuur Willem

**Comment by idealhack** [comment]
Happen to saw [Hatchful](https://hatchful.shopify.com) today, so I create a logo with three different colors, to use as avatars for the bot, channel, and group. Files were committed to the [design](
https://github.com/magunetto/design) repo.
